formatter: "markdown table"
settings:
  anchor: true
  hide-empty: true
  html: false
  lockfile: true
  requiered: true
  sensetive: true
  type: true
sort:
  enabled: true
  by: name
output:
  file: README.md
  mode: inject